package com.learning.gym.star.gym.controller;

import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import java.sql.SQLIntegrityConstraintViolationException;

@ControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(EmptyResultDataAccessException.class)
    public ResponseEntity handleAccessingNotExistingRecord(){
        return new ResponseEntity<>("FileNotFound", HttpStatus.NOT_FOUND);
    }

    @ExceptionHandler(SQLIntegrityConstraintViolationException.class)
    public ResponseEntity handleDuplicatedId(){
        return new ResponseEntity<>("This id is occupied. Leave gym id empty and it will be autogenerated.", HttpStatus.BAD_REQUEST);
    }
}
